select TAX as TAXID, TAX.ITSNAME as TAXNAME, INVITEMTAXCATEGORYLINE.ITSPERCENTAGE, sum(SUBT) as SUBTOTAL
from
( select TXCAT, SUBT
  from CARTLN
  where TXCAT is not null and DISAB=0 and SEL:CONDSEL and ITSOWNER=:CARTID
) as ALL_LINES
join INVITEMTAXCATEGORY on INVITEMTAXCATEGORY.ITSID=TXCAT
join INVITEMTAXCATEGORYLINE on INVITEMTAXCATEGORYLINE.ITSOWNER=INVITEMTAXCATEGORY.ITSID
join TAX on INVITEMTAXCATEGORYLINE.TAX=TAX.ITSID
group by TAXID, TAXNAME, INVITEMTAXCATEGORYLINE.ITSPERCENTAGE;
