select SELLER, TXCAT as TAXCATID, TAX as TAXID, ITSPERCENTAGE, sum(SUBT) as SUBTOTAL, sum(TOT) as ITSTOTAL
from
( select SELLER, TXCAT, SUBT, TOT
  from CARTLN
  where TXCAT is not null and DISAB=0 and ITSOWNER=:CARTID
) as ALL_LINES
join INVITEMTAXCATEGORY on INVITEMTAXCATEGORY.ITSID=TXCAT
join INVITEMTAXCATEGORYLINE on INVITEMTAXCATEGORYLINE.ITSOWNER=INVITEMTAXCATEGORY.ITSID
group by SELLER, TAXCATID, TAXID, ITSPERCENTAGE;
