select TAX as TAXID, TAX.ITSNAME as TAXNAME, sum(TOT) as TOTALTAX
from CARTITTXLN where DISAB=0 and SELLERID:CONDSEL and CARTID=:CARTID
join TAX on INVITEMTAXCATEGORYLINE.TAX=TAX.ITSID
group by TAXID, TAXNAME;
