select count(*) as TOTALROWS
from (
  select ITEMID
  from ITEMINLIST
  where AVAILABLEQUANTITY>0 and ITSTYPE=0 :WHEREADD
 ) as ALLGOODS
join (
  select distinct GOODS as GOODSINCATALOG from GOODSCATALOGS where ITSCATALOG:CATALOGFILTER
 ) as GOODSINCATALOGALL on GOODSINCATALOGALL.GOODSINCATALOG=ALLGOODS.ITEMID
