select ITSTYPE, ITALL.ITEMID as ITEMID, IMAGEURL, ITSPRICE, PREVIOUSPRICE, AVAILABLEQUANTITY, ITSRATING, DETAILSMETHOD,
  case when I18NSPECIFICINLIST.ITSNAME is null then ITALL.ITSNAME else I18NSPECIFICINLIST.ITSNAME end as ITSNAME,
  case when I18NSPECIFICINLIST.SPECIFICINLIST is null then ITALL.SPECIFICINLIST else I18NSPECIFICINLIST.SPECIFICINLIST end as SPECIFICINLIST
from (
  select ITSTYPE, ITEMID, ITSNAME, IMAGEURL, SPECIFICINLIST, ITSPRICE, PREVIOUSPRICE, AVAILABLEQUANTITY, ITSRATING, DETAILSMETHOD
  from ITEMINLIST
  where AVAILABLEQUANTITY>0 and ITSTYPE=:ITTYP :WHEREADD
 ) as ITALL
join (
  select distinct ITEM as ITINCAT from :TITCAT where ITSCATALOG:CATALOGFILTER
 ) as ITINCATALL on ITINCATALL.ITINCAT=ITALL.ITEMID
left join (
  select ITSNAME, SPECIFICINLIST, ITEMID from I18NSPECIFICINLIST  where ITSTYPE=:ITTYP and LANG=':LANG'
 ) as I18NSPECIFICINLIST on I18NSPECIFICINLIST.ITEMID=ITALL.ITEMID
