select ITEMID, ITSPRICE
from (
  select ITEMID, ITSPRICE
  from ITEMINLIST
  where AVAILABLEQUANTITY>0 and ITSTYPE=:ITTYP :WHEREADD
 ) as ITALL
join (
  select distinct ITEM as ITINCAT from :TITCAT where ITSCATALOG:CATALOGFILTER
 ) as ITINCATALL on ITINCATALL.ITINCAT=ITALL.ITEMID
