select ITSID, GOOD, ITSNAME, ITSOWNER, PRICE, TOT, TOTTX, UOM.ITSNAME as UOMITSNAME, UOM.ITSID as UOMITSID,
case when AVQUAN is null or QUANT>AVQUAN then 0 else QUANT end as QUANT
from CUSTORDERGDLN
left join UNITOFMEASURE as UOM on CUSTORDERGDLN.UOM=UOM.ITSID
left join (select ITEM, ITSQUANTITY as AVQUAN from GOODSPLACE where PICKUPPLACE=:PLACE) as ITPL on ITPL.ITEM=GOOD
where ITSOWNER in (:ORIDS);
