select CUSTORDERSRVLN.ITSID as ITSID, CUSTORDERSRVLN.ITSNAME as ITSNAME, SERVICE, ITSOWNER, PRICE, TOT, TOTTX, UOM.ITSNAME as UOMITSNAME, UOM.ITSID as UOMITSID, DT1, DT2,
case when AVQUAN is null or QUANT>AVQUAN then 0 else QUANT end as QUANT
from CUSTORDERSRVLN
left join UNITOFMEASURE as UOM on CUSTORDERSRVLN.UOM=UOM.ITSID
left join (select ITEM, ITSQUANTITY as AVQUAN from SERVICEPLACE where PICKUPPLACE=:PLACE) as ITPL on ITPL.ITEM=SERVICE
where ITSOWNER in (:ORIDS);
