select count(*) as TOTALROWS
from (
  select ITEMID
  from ITEMINLIST
  where AVAILABLEQUANTITY>0 and ITSTYPE=2 :WHEREADD
 ) as ALLSEGOOD
join (
  select distinct ITEM as SEGOODINCATALOG from SEGOODCATALOG where ITSCATALOG:CATALOGFILTER
 ) as SEGOODINCATALOGALL on SEGOODINCATALOGALL.SEGOODINCATALOG=ALLSEGOOD.ITEMID
