select count(*) as TOTALROWS
from (
  select ITEMID
  from ITEMINLIST
  where AVAILABLEQUANTITY>0 and ITSTYPE=1 :WHEREADD
 ) as ALLSERVICE
join (
  select distinct ITEM as SERVICEINCATALOG from SERVICECATALOG where ITSCATALOG:CATALOGFILTER
 ) as SERVICEINCATALOGALL on SERVICEINCATALOGALL.SERVICEINCATALOG=ALLSERVICE.ITEMID
