join (
  select ITEM as SEGOODSFORSPEC
  from SEGOODSSPECIFICS
  where :WHERESPGDFILTER
  group by ITEM
  having count(ITEM)=:SPGDFILTERCOUNT
 ) as SEGOODSFORSPECALL on SEGOODSINCATALOGALL.SEGOODINCATALOG=SEGOODSFORSPECALL.SEGOODSFORSPEC
