join (
  select ITEM as GOODSFORSPEC
  from GOODSSPECIFICS
  where :WHERESPGDFILTER
  group by ITEM
  having count(ITEM)=:SPGDFILTERCOUNT
 ) as GOODSFORSPECALL on GOODSINCATALOGALL.GOODSINCATALOG=GOODSFORSPECALL.GOODSFORSPEC
