join (
  select GOODS as GOODSFORSPEC
  from GOODSSPECIFIC
  where :WHERESPGDFILTER
  group by GOODS
  having count(GOODS)=:SPGDFILTERCOUNT
 ) as GOODSFORSPECALL on GOODSINCATALOGALL.GOODSINCATALOG=GOODSFORSPECALL.GOODSFORSPEC
