join (
  select ITEM as SERVICEFORSPEC
  from SERVICESPECIFICS
  where :WHERESPGDFILTER
  group by ITEM
  having count(ITEM)=:SPGDFILTERCOUNT
 ) as SERVICEFORSPECALL on SERVICEINCATALOGALL.SERVICEINCATALOG=SERVICEFORSPECALL.SERVICEFORSPEC
