alter table SETTINGSADD add column SPECSEPARATOR text not null default ',';
alter table SETTINGSADD add column SPECGRSEPARATOR text default null;
alter table SETTINGSADD add column SPECHTMLSTART text default null;
alter table SETTINGSADD add column SPECHTMLEND text default null;
alter table SETTINGSADD add column SPECGRHTMLSTART text default null;
alter table SETTINGSADD add column SPECGRHTMLEND text default null;
alter table GOODSINLISTLUV add column SERVICESPECIFICLUV integer default null;
alter table GOODSINLISTLUV add column SERVICEPRICELUV integer default null;
alter table GOODSINLISTLUV add column SERVICEPLACELUV integer default null;
alter table GOODSINLISTLUV add column SERVICERATINGLUV integer default null;
alter table SPECIFICSOFITEM add column TEMPHTML integer default null references HTMLTEMPLATE(ITSID);
alter table ITEMINLIST add column UNITOFMEASURE integer default null references UNITOFMEASURE(ITSID);
alter table I18NSPECIFICINLIST add column ITSNAME text;
drop table GOODSSPECIFIC;
drop table GOODSCATALOGS;
drop table GOODSPRICE;
drop table GOODSAVAILABLE;
update GOODSINLISTLUV set GOODSAVAILABLELUV=null;
update DATABASEINFO set DATABASEVERSION=7, DESCRIPTION='Beige Accounting OIO DB version 7';
