alter table DEBTORCREDITOR add column ISFOREIGNER integer not null default 0;
alter table TRADINGSETTINGS add column DEFAULTPAYMENTMETHOD integer not null default 0;
alter table SPECIFICSOFITEM add column CHOOSEABLESPECIFICSTYPE integer default null references CHOOSEABLESPECIFICSTYPE(ITSID);
alter table CHOOSEABLESPECIFICSTYPE add column HTMLTEMPLATE integer default null references HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATESTART integer default null references HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEEND integer default null references HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEDETAIL integer default null references HTMLTEMPLATE(ITSID);
alter table PICKUPPLACE add column LATITUDE real default null;
alter table PICKUPPLACE add column LONGITUDE real default null;
alter table ITEMINLIST add column DETAILSMETHOD integer default null;
alter table GOODSSPECIFIC add column STRINGVALUE3 text default null;
alter table GOODSSPECIFIC add column STRINGVALUE4 text default null;
update DATABASEINFO set DATABASEVERSION=6, DESCRIPTION='Beige Accounting OIO DB version 6';
