drop table CUSTOMERORDERTAXLINE;
drop table CUSTOMERORDERSESERVICE;
drop table CUSTOMERORDERSERVICE;
drop table CUSTOMERORDERSEGOODS;
drop table CUSTOMERORDERGOODS;
drop table CUSTOMERORDER;
drop table CARTTAXLINE;
drop table CARTITEM;
drop table SHOPPINGCART;
alter table GOODSINLISTLUV add column SESERVICESPECIFICLUV integer default null;
alter table GOODSINLISTLUV add column SESERVICEPRICELUV integer default null;
alter table GOODSINLISTLUV add column SESERVICEPLACELUV integer default null;
alter table GOODSINLISTLUV add column SESERVICERATINGLUV integer default null;
alter table GOODSINLISTLUV add column SEGOODSPECIFICLUV integer default null;
alter table GOODSINLISTLUV add column SEGOODPRICELUV integer default null;
alter table GOODSINLISTLUV add column SEGOODPLACELUV integer default null;
alter table GOODSINLISTLUV add column SEGOODRATINGLUV integer default null;
alter table SESERVICEPRICE add column DECPLACES integer default 0;
alter table SESERVICEPRICE add column USTEP real default 1;
alter table SEGOODSPRICE add column DECPLACES integer default 0;
alter table SEGOODSPRICE add column USTEP real default 1;
alter table SERVICEPRICE add column DECPLACES integer default 0;
alter table SERVICEPRICE add column USTEP real default 1;
alter table PRICEGOODS add column DECPLACES integer default 0;
alter table PRICEGOODS add column USTEP real default 1;
alter table TAXDESTINATION add column REGZIP text;
alter table ONLINEBUYER add column TIN text;
alter table ONLINEBUYER add column FOREIG integer not null default 0;
alter table ONLINEBUYER add column TAXDEST integer default null references TAXDESTINATION(ITSID);
update DATABASEINFO set DATABASEVERSION=8, DESCRIPTION='Beige Accounting OIO DB version 8';
