alter table SALESINVOICESERVICELINE add column UNITOFMEASURE integer not null default 1 references UNITOFMEASURE(ITSID);
alter table SALESINVOICESERVICELINE add column ITSQUANTITY real not null default 1;
alter table SALESINVOICESERVICELINE add column SUBTOTAL real not null default 0;
alter table PURCHASEINVOICESERVICELINE add column UNITOFMEASURE integer not null default 1 references UNITOFMEASURE(ITSID);
alter table PURCHASEINVOICESERVICELINE add column ITSQUANTITY real not null default 1;
alter table PURCHASEINVOICESERVICELINE add column SUBTOTAL real not null default 0;
alter table DEBTORCREDITOR add column ISFOREIGNER integer not null default 0;
alter table TRADINGSETTINGS add column DEFAULTPAYMENTMETHOD integer not null default 0;
alter table TRADINGSETTINGS add column USEADVANCEDI18N integer not null default 0;
alter table ACCSETTINGS add column PRINTCURRENCYLEFT integer not null default 0;
alter table ACCSETTINGS add column USECURRENCYSIGN integer not null default 0;
alter table SPECIFICSOFITEM add column CHOOSEABLESPECIFICSTYPE integer default null references CHOOSEABLESPECIFICSTYPE(ITSID);
alter table CHOOSEABLESPECIFICSTYPE add column HTMLTEMPLATE integer default null references HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATESTART integer default null references HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEEND integer default null references HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEDETAIL integer default null references HTMLTEMPLATE(ITSID);
alter table PICKUPPLACE add column LATITUDE real default null;
alter table PICKUPPLACE add column LONGITUDE real default null;
alter table ITEMINLIST add column DETAILSMETHOD integer default null;
alter table GOODSSPECIFIC add column STRINGVALUE3 text default null;
alter table GOODSSPECIFIC add column STRINGVALUE4 text default null;
alter table SPECIFICSOFITEM add column USEFORORDERING integer not null default 0;
alter table PICKUPPLACE add column TIMEZONE integer default null;
alter table SETTINGSADD add column MINIMUMLISTSIZEFORORDERING integer not null default 20;
alter table CATALOGGS add column USEFILTERSPECIFICS integer not null default 0;
alter table CATALOGGS add column USEFILTERSUBCATALOG integer not null default 0;
alter table CATALOGGS add column USEPICKUPPLACEFILTER integer not null default 0;
alter table CATALOGGS add column USEAVAILABLEFILTER integer not null default 0;
alter table CATALOGGS add column FILTERPRICEID integer default null;
alter table CURRENCY add column ITSSIGN text default null;
update CURRENCY set ITSSIGN='€', ITSVERSION=(ITSVERSION+1) where ITSID=978;
update CURRENCY set ITSSIGN='$', ITSVERSION=(ITSVERSION+1) where ITSID=840;
update CURRENCY set ITSSIGN='₽', ITSVERSION=(ITSVERSION+1) where ITSID=643;
insert into LANGUAGES (ITSID, ITSNAME, ITSVERSION) values ('ru', 'Русский', 1462867931627);
insert into LANGUAGES (ITSID, ITSNAME, ITSVERSION) values ('en', 'English', 1462867931627);
insert into COUNTRIES (ITSID, ITSNAME, ITSVERSION) values ('US', 'USA', 1462867931627);
insert into COUNTRIES (ITSID, ITSNAME, ITSVERSION) values ('RU', 'РФ', 1462867931627);
insert into DECIMALSEPARATOR (ITSID, ITSNAME, ITSVERSION) values (',', 'comma', 1462867931627);
insert into DECIMALSEPARATOR (ITSID, ITSNAME, ITSVERSION) values ('.', 'dot', 1462867931627);
insert into DECIMALGROUPSEPARATOR (ITSID, ITSNAME, ITSVERSION) values (',', 'comma', 1462867931627);
insert into DECIMALGROUPSEPARATOR (ITSID, ITSNAME, ITSVERSION) values ('space', 'space', 1462867931627);
insert into LANGPREFERENCES (DECIMALGROUPSEP, LANG, COUNTRY, DECIMALSEP, ISDEFAULT, ITSVERSION, DIGITSINGROUP) values (',', 'en', 'US', '.', 1, 1462867931627, 3);
insert into LANGPREFERENCES (DECIMALGROUPSEP, LANG, COUNTRY, DECIMALSEP, ISDEFAULT, ITSVERSION, DIGITSINGROUP) values ('space', 'ru', 'RU', ',', 0, 1462867931627, 3);
update SALESINVOICESERVICELINE set SUBTOTAL=ITSPRICE, ITSVERSION=(ITSVERSION+1) where SUBTOTAL=0;
insert into ACCENTRIESSOURCESLINE (ITSID, ITSOWNER, FILENAME, ITSVERSION, SOURCETYPE, SETCODE, ISUSED, ENTRIESSOURCETYPE, ENTRIESACCOUNTINGTYPE, SOURCEIDNAME, DESCRIPTION) values (25, 1, 'PurInvInvCatPayDbtCrdtAccrMSm', 1462867931627, 1, 'InvItemCategory,DebtorCreditor', 1, 0, 1, 'PURCHASEINVOICE.ITSID', 'PurchaseInvoice, Debit Inventory per InvItemCategory, Credit AccPayable per DebtorCreditor for Subtotal amount. Accrual Symmetric.');
insert into ACCENTRIESSOURCESLINE (ITSID, ITSOWNER, FILENAME, ITSVERSION, SOURCETYPE, SETCODE, ISUSED, ENTRIESSOURCETYPE, ENTRIESACCOUNTINGTYPE, SOURCEIDNAME, DESCRIPTION) values (26, 1, 'PurInvSalTaxDbtAccPayCrAccrMSm', 1462867931627, 1, 'Tax,DebtorCreditor', 1, 0, 1, 'PURCHASEINVOICE.ITSID', 'PurchaseInvoice, Debit SalesTaxFromPurchase per Tax, Credit AccPayable per DebtorCreditor for Tax amount. Accrual Symmetric.');
insert into ACCENTRIESSOURCESLINE (ITSID, ITSOWNER, FILENAME, ITSVERSION, SOURCETYPE, SETCODE, ISUSED, ENTRIESSOURCETYPE, ENTRIESACCOUNTINGTYPE, SOURCEIDNAME, DESCRIPTION) values (27, 1, 'PurInvExpenceDbtAccPayCrAccrMSm', 1462867931627, 1, 'Expense,DebtorCreditor', 1, 0, 1, 'PURCHASEINVOICE.ITSID', 'PurchaseInvoice , Debit AccExpense per ServicePurchasedCategory.Expense, Credit AccPayable per DebtorCreditor for Subtotal amount. Accrual Symmetric.');
insert into ACCENTRIESSOURCESLINE (ITSID, ITSOWNER, FILENAME, ITSVERSION, SOURCETYPE, SETCODE, ISUSED, ENTRIESSOURCETYPE, ENTRIESACCOUNTINGTYPE, SOURCEIDNAME, DESCRIPTION) values (28, 1, 'PurInvSalTaxDbtAccPayCrCashMSm', 1462867931627, 1, 'Tax,DebtorCreditor', 0, 0, 1, 'PURCHASEINVOICE.ITSID', 'PurchaseInvoice, Debit SalesTaxFromPurchase per Tax, Credit AccPayable per DebtorCreditor for Tax amount. Cash Symmetric.');
insert into ACCENTRIESSOURCESLINE (ITSID, ITSOWNER, FILENAME, ITSVERSION, SOURCETYPE, SETCODE, ISUSED, ENTRIESSOURCETYPE, ENTRIESACCOUNTINGTYPE, SOURCEIDNAME, DESCRIPTION) values (29, 1, 'PaymentToSalTaxDbtAccPayCrCashMSm', 1462867931627, 8, 'Tax,DebtorCreditor', 0, 0, 1, 'PAYMENTTO.ITSID', 'PaymentTo, Debit SalesTaxFromPurchase per Tax, Credit AccPayable per DebtorCreditor for Tax amount. Cash Symmetric.');
update DATABASEINFO set DATABASEVERSION=6, DESCRIPTION='Beige Accounting OIO DB version 6';
