alter table DEBTORCREDITOR add column ISFOREIGNER integer not null default 0;
alter table TRADINGSETTINGS add column DEFAULTPAYMENTMETHOD integer not null default 0;
alter table SPECIFICSOFITEM add column CHOOSEABLESPECIFICSTYPE bigint default null;
alter table SPECIFICSOFITEM add constraint fkspecofitchsptp FOREIGN KEY (CHOOSEABLESPECIFICSTYPE) REFERENCES CHOOSEABLESPECIFICSTYPE(ITSID);
alter table CHOOSEABLESPECIFICSTYPE add column HTMLTEMPLATE bigint default null;
alter table CHOOSEABLESPECIFICSTYPE add constraint fkchspectyphtmltmp FOREIGN KEY (HTMLTEMPLATE) REFERENCES HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATESTART bigint default null;
alter table SPECIFICSOFITEMGROUP add constraint fkspoigrtmpst FOREIGN KEY (TEMPLATESTART) REFERENCES HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEEND bigint default null;
alter table SPECIFICSOFITEMGROUP add constraint fkspoigrtmpend FOREIGN KEY (TEMPLATEEND) REFERENCES HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEDETAIL bigint default null;
alter table SPECIFICSOFITEMGROUP add constraint fkspoigrtmdet FOREIGN KEY (TEMPLATEDETAIL) REFERENCES HTMLTEMPLATE(ITSID);
alter table PICKUPPLACE add column LATITUDE decimal(2,6) default null;
alter table PICKUPPLACE add column LONGITUDE decimal(3,6) default null;
alter table ITEMINLIST add column DETAILSMETHOD integer null default not;
update DATABASEINFO set DATABASEVERSION=6, DESCRIPTION='Beige Accounting OIO DB version 6';
