alter table GOODSINLISTLUV add column SESERVICESPECIFICLUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICEPRICELUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICEPLACELUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICERATINGLUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODSPECIFICLUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODPRICELUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODPLACELUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODRATINGLUV bigint default null;
alter table SESERVICEPRICE add column DECPLACES integer default 0;
alter table SESERVICEPRICE add column PERUNIT decimal(9,4) default 1;
alter table SESERVICEPRICE add column USTEP decimal(9,4) default 1;
alter table SEGOODSPRICE add column DECPLACES integer default 0;
alter table SEGOODSPRICE add column PERUNIT decimal(9,4) default 1;
alter table SEGOODSPRICE add column USTEP decimal(9,4) default 1;
alter table SERVICEPRICE add column DECPLACES integer default 0;
alter table SERVICEPRICE add column PERUNIT decimal(9,4) default 1;
alter table SERVICEPRICE add column USTEP decimal(9,4) default 1;
alter table PRICEGOODS add column DECPLACES integer default 0;
alter table PRICEGOODS add column PERUNIT decimal(9,4) default 1;
alter table PRICEGOODS add column USTEP decimal(9,4) default 1;
alter table TAXDESTINATION add column REGZIP varchar(10);
update DATABASEINFO set DATABASEVERSION=8, DESCRIPTION='Beige Accounting OIO DB version 8';
