alter table SETTINGSADD add column SPECSEPARATOR varchar(50) not null default ',';
alter table SETTINGSADD add column SPECGRSEPARATOR varchar(50) default null;
alter table SETTINGSADD add column SPECHTMLSTART varchar(255) default null;
alter table SETTINGSADD add column SPECHTMLEND varchar(255) default null;
alter table SETTINGSADD add column SPECGRHTMLSTART varchar(255) default null;
alter table SETTINGSADD add column SPECGRHTMLEND varchar(255) default null;
alter table GOODSINLISTLUV add column SERVICESPECIFICLUV bigint default null;
alter table GOODSINLISTLUV add column SERVICEPRICELUV bigint default null;
alter table GOODSINLISTLUV add column SERVICEPLACELUV bigint default null;
alter table GOODSINLISTLUV add column SERVICERATINGLUV bigint default null;
alter table SPECIFICSOFITEM add column TEMPHTML bigint default null;
alter table SPECIFICSOFITEM add constraint fkspoitmplspd FOREIGN KEY (TEMPHTML) REFERENCES HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEM add column UNITOFMEASURE bigint default null;
alter table SPECIFICSOFITEM add constraint fkspoitmpuom FOREIGN KEY (UNITOFMEASURE) REFERENCES UNITOFMEASURE(ITSID);
alter table I18NSPECIFICINLIST add column ITSNAME varchar(255);
update DATABASEINFO set DATABASEVERSION=7, DESCRIPTION='Beige Accounting OIO DB version 7';
