alter table GOODSINLISTLUV add column SESERVICESPECIFICLUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICEPRICELUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICEPLACELUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICERATINGLUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODSPECIFICLUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODPRICELUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODPLACELUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODRATINGLUV bigint default null;
alter table SESERVICEPRICE add column UNSTEP decimal(9,4) default 1;
alter table SEGOODSPRICE add column UNSTEP decimal(9,4) default 1;
alter table SERVICEPRICE add column UNSTEP decimal(9,4) default 1;
alter table PRICEGOODS add column UNSTEP decimal(9,4) default 1;
alter table ITEMINLIST add column UNSTEP decimal(9,4) default 1;
alter table TAXDESTINATION add column REGZIP varchar(10);
alter table ONLINEBUYER add column TIN varchar(10);
alter table ONLINEBUYER add column FOREIG tinyint not null default 0;
alter table ONLINEBUYER add column TAXDEST bigint default null;
alter table ONLINEBUYER add constraint fkonlbtxdest FOREIGN KEY (TAXDEST) references TAXDESTINATION(ITSID);
drop table CUSTOMERORDERTAXLINE;
drop table CUSTOMERORDERSESERVICE;
drop table CUSTOMERORDERSERVICE;
drop table CUSTOMERORDERSEGOODS;
drop table CUSTOMERORDERGOODS;
drop table CUSTOMERORDER;
drop table CARTTAXLINE;
drop table CARTITEM;
drop table SHOPPINGCART;
update DATABASEINFO set DATABASEVERSION=8, DESCRIPTION='Beige Accounting OIO DB version 8';
