alter table DEBTORCREDITOR add column ISFOREIGNER tinyint not null default 0;
alter table TRADINGSETTINGS add column DEFAULTPAYMENTMETHOD tinyint not null default 0;
alter table SPECIFICSOFITEM add column CHOOSEABLESPECIFICSTYPE bigint unsigned default null;
alter table SPECIFICSOFITEM add FOREIGN KEY (CHOOSEABLESPECIFICSTYPE) REFERENCES CHOOSEABLESPECIFICSTYPE(ITSID);
alter table CHOOSEABLESPECIFICSTYPE add column HTMLTEMPLATE bigint unsigned default null;
alter table CHOOSEABLESPECIFICSTYPE add FOREIGN KEY (HTMLTEMPLATE) REFERENCES HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATESTART bigint unsigned default null;
alter table SPECIFICSOFITEMGROUP add FOREIGN KEY (TEMPLATESTART) REFERENCES HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEEND bigint unsigned default null;
alter table SPECIFICSOFITEMGROUP add FOREIGN KEY (TEMPLATEEND) REFERENCES HTMLTEMPLATE(ITSID);
alter table SPECIFICSOFITEMGROUP add column TEMPLATEDETAIL bigint unsigned default null;
alter table SPECIFICSOFITEMGROUP add FOREIGN KEY (TEMPLATEDETAIL) REFERENCES HTMLTEMPLATE(ITSID);
alter table PICKUPPLACE add column LATITUDE decimal(2,6) default null;
alter table PICKUPPLACE add column LONGITUDE decimal(3,6) default null;
alter table ITEMINLIST add column DETAILSMETHOD int default null;
alter table GOODSSPECIFIC add column STRINGVALUE3 varchar(255) default null;
alter table GOODSSPECIFIC add column STRINGVALUE4 varchar(255) default null;
update DATABASEINFO set DATABASEVERSION=6, DESCRIPTION='Beige Accounting OIO DB version 6';
