alter table GOODSINLISTLUV add column SESERVICESPECIFICLUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICEPRICELUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICEPLACELUV bigint default null;
alter table GOODSINLISTLUV add column SESERVICERATINGLUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODSPECIFICLUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODPRICELUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODPLACELUV bigint default null;
alter table GOODSINLISTLUV add column SEGOODRATINGLUV bigint default null;
alter table SESERVICEPRICE add column DECPLACES integer default 0;
alter table SESERVICEPRICE add column USTEP decimal(9,4) default 1;
alter table SEGOODSPRICE add column DECPLACES integer default 0;
alter table SEGOODSPRICE add column USTEP decimal(9,4) default 1;
alter table SERVICEPRICE add column DECPLACES integer default 0;
alter table SERVICEPRICE add column USTEP decimal(9,4) default 1;
alter table PRICEGOODS add column DECPLACES integer default 0;
alter table PRICEGOODS add column USTEP decimal(9,4) default 1;
alter table TAXDESTINATION add column REGZIP varchar(10);
alter table ONLINEBUYER add column  varchar(10);
alter table ONLINEBUYER add column FOREIG tinyint not null default 0;
alter table ONLINEBUYER add column TAXDEST bigint unsigned default null;
alter table ONLINEBUYER add FOREIGN KEY (TAXDEST) references TAXDESTINATION(ITSID);;
set FOREIGN_KEY_CHECKS=0;
drop table CUSTOMERORDERTAXLINE;
drop table CUSTOMERORDERSESERVICE;
drop table CUSTOMERORDERSERVICE;
drop table CUSTOMERORDERSEGOODS;
drop table CUSTOMERORDERGOODS;
drop table CUSTOMERORDER;
drop table CARTTAXLINE;
drop table CARTITEM;
drop table SHOPPINGCART;
set FOREIGN_KEY_CHECKS=1;
update DATABASEINFO set DATABASEVERSION=8, DESCRIPTION='Beige Accounting OIO DB version 8';
